### PR TITLE
Get self reference modules working

### PR DESCRIPTION
**Pull request by MylesBorins**
I was partially confused due to a potential spec bug
in package.exports that didn't take into account top-level
application (without a . main)

This now works and has a passing test.

Refs: https://github.com/nodejs/node/issues/30633

### CODE REVIEW

**Comment by DerekNonGeneric** [comment]
@MylesBorins, I cloned your branch and ran the test locally. It is failing on my machine. Could this have to do with the `~/package.json` hack?

**Comment by MylesBorins** [comment]
That is exactly why it is failing. Have not figured out why that breaks it
yet... Definitely a weirdo bug

**Comment by DerekNonGeneric** [comment]
I will take it from here and investigate further, thanks!

**Comment by fusionstrings** [comment]
Hi @MylesBorins and @DerekNonGeneric 

I ended up here while following the trails of `LOAD_SELF_REFERENCE` from here https://nodejs.org/dist/latest-v13.x/docs/api/modules.html and https://github.com/nodejs/node/pull/31009

I was looking into the implementation to get help on my quest to get 'self reference" working from here https://github.com/MylesBorins/lorem-demo/tree/fc5ed2558670028e3c5bb02f2ae098044d63212a

The implementation uses `--no-esm` and test fails in absence of it. Does it mean that self resolution is non-ESM feature?

**Comment by DerekNonGeneric** [comment]
Hello @fusionstrings, glad you found your way here!

> Does it mean that self resolution is non-ESM feature?

Nope, it definitely works with `import` too!

Here's a brief explanation that might help clarify what's being described above.

The `--no-esm` flag disables '-r esm' behavior by switching off the `--esm` flag, which is on by default. This '-r esm' behavior would preload the `esm` module at startup. The `esm`, module, which is a userland loader to polyfill versions of Node.js without native support for ES Modules, is no longer necessary in v13.2+. This is because the majority of the ES module implementation is unflagged in the 13.x release line.

I would recommend checking out the master branch of this repository (the one attached to this thread) to see a currently functional implementation. Just make sure you're on v13.2+. It should be working! I know how confusing this can be, so I've dropped some links below that I hope will clarify what I've written above. Ultimately, the cause of it not working on my end was that the integrated VSCode terminal, which I was using to test this behavior, was using the wrong version.

Let me know if there's anything else. :)

- `--no-esm` [§](https://github.com/tapjs/node-tap/commit/040f61f213961ce3e94a865057a87494e2e2eb1f) 
- `-r`, `--require module` [§](https://nodejs.org/api/cli.html#cli_r_require_module)
- `esm`, module [§](https://www.npmjs.com/package/esm)
- v13.2 Unflagging announcement [§](https://github.com/nodejs/modules/blob/master/doc/unflagging-announcement.md)

Note: the `esm` module _does not_ put your code in `module` context. It is still in `commonjs` context, and I would advise against using it if you are interested in testing the new ES module implementation.

**Comment by fusionstrings** [comment]
Thanks a lot @DerekNonGeneric for explaining in detail especially about significance of `--no-esm`.

I got it working now 👍

**Comment by MylesBorins** [comment]
One thing to add --no-esm is a tap specific flag... Not for the nodejs
runtime

**Comment by fusionstrings** [comment]
@MylesBorins Thanks for clarifying. 

The issue with me was extremely weird. I matched with the code in master branch of https://github.com/DerekNonGeneric/loader339 and my code was using same convention.

As @DerekNonGeneric mentioned that he was using VSCode integrated terminal, so was I. 
I use nvm and ensured correct version was activated.

I still can't figure out what was wrong 😢but a restart seems to have fixed it for me.
Assurance that master branch has working code ensured that something is wrong from my side.

**Pull request merged**
